import 'package:flutter/material.dart';
import 'package:song_recommender_ai/utils/res/colors.dart';

class FAQPage extends StatelessWidget {
  const FAQPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('FAQ'),
      ),
      body: Container(
        padding: const EdgeInsets.all(16.0),
        color: Colors.white,
        child: ListView(
          children: const [
            FAQCard(
              question:
                  'What makes SongScript different from other music recommendation apps?',
              answer:
                  'SongScript stands out because it creates personalized music playlists based on your words. Simply describe your mood, feelings, or a specific vibe, and SongScript transforms your text into unique, tailored playlists.',
            ),
            FAQCard(
              question: 'Can I save the playlists generated by SongScript?',
              answer:
                  'Absolutely! Songscript automatically saves your favorite tracks and playlists to your profile. They are all acessible from your navigation bar easily.',
            ),
            FAQCard(
              question:
                  'How does SongScript select the songs for my playlists?',
              answer:
                  'SongScript uses advanced algorithms and AI technology to analyze your input. Based on the mood, emotions, or specific details you provide, SongScript generates a playlist that matches your description. The more you use SongScript, the more it learns about your preferences and the better it gets at creating playlists that you love.',
            ),
          ],
        ),
      ),
    );
  }
}

class FAQCard extends StatelessWidget {
  final String question;
  final String answer;

  const FAQCard({super.key, required this.question, required this.answer});

  @override
  Widget build(BuildContext context) {
    return Card(
      elevation: 3, // Add a shadow to the card
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(10.0), // Add rounded corners
      ),
      child: ExpansionTile(
        title: Text(
          question,
          style: const TextStyle(
            fontWeight: FontWeight.bold,
            fontSize: 18.0,
          ),
        ),
        tilePadding: const EdgeInsets.symmetric(horizontal: 16.0),
        backgroundColor: AppColors.aiWidgetColor,
        children: <Widget>[
          Padding(
            padding: const EdgeInsets.all(16.0),
            child: Text(answer,
                style: const TextStyle(
                  fontSize: 16.0,
                )),
          ),
        ],
      ),
    );
  }
}
